version: 2
formats: []

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

python:
    version: 3
    install:
        - requirements: source/requirements.txt
        - method: pip
          path: .
